### ISSUE TITLE
Make empty categories show a message

### ISSUE THREAD

**Issue by neckcen** [stanipintjuk/Silverfish#12]
Currently empty categories show absolutely nothing which looks a bit odd. I'd suggest adding a small message along the lines of "This category is currently empty. You can move apps between categories by dragging them."

**Comment by Lonami** [comment]
It's a good idea, maybe something like "This tab is empty. Drag applications here to add some".

**Comment by stanipintjuk** [comment]
Very good idea! I just added the message. Tell me what you think :)
