### ISSUE TITLE
Add a way to support the authors

### ISSUE THREAD

**Issue by neckcen** [stanipintjuk/Silverfish#13]
Just when Smartlauncher pushes yet more bloat and ads, you come up with this free project. I'd love to be able to support the authors (bounties, paypal, patreon, etc).

**Comment by stanipintjuk** [comment]
Oh boy, oh boy. I really appreciate that you like this project so much, but idk, maybe when version 1.0 is finnished we'll add a patreon or something. But atm I don't think this project deserves/needs/[is motivated by] any money.
