### ISSUE TITLE
Temporary duplicated icons

### ISSUE THREAD

**Issue by Lonami** [stanipintjuk/Silverfish#19]
Sometimes the icons appear as duplicated. It's not a big deal, since switching to another tab and then back again to the previous one fixes it, but it still happens.
### Steps to reproduce

Drag an application into another category. Don't drop it. Quickly drag it back to the previous category before it loads. If it didn't duplicate the app, keep trying.
### Proof:

![photo_2016-08-12_18-24-48](https://cloud.githubusercontent.com/assets/6297805/17629392/696891e4-60ba-11e6-8dd5-13e6a5659918.jpg)

**Comment by stanipintjuk** [comment]
Does this happen after the rewrite?

**Comment by Lonami** [comment]
Yes, I was testing your latest pull request. But this also happened before!

**Comment by stanipintjuk** [comment]
When I do that it doesnt duplicate but instead is removed from that tab and placed in the first tab

**Comment by Lonami** [comment]
Don't drop them in the second tab, simply hover it so it "switches" to it, but don't drop the app. Then carry on swiping your finger up to the first tab and drop the app there. I can easily replicate it. See below:
![out](https://cloud.githubusercontent.com/assets/6297805/17632537/2ce25ee4-60c9-11e6-9965-ff3dbb64caf1.gif)

**Comment by Lonami** [comment]
Also, did you notice that the androidVNC application has disappeared at the very end?

**Comment by stanipintjuk** [comment]
Oh I see.. it only works in the first tab

If you try to do it in a different tab then you'll notice that there is a different bug :P

**Comment by Lonami** [comment]
It goes back to the first tab, right?

**Comment by stanipintjuk** [comment]
yup

**Comment by stanipintjuk** [comment]
It should be fixed now. Try agian

**Comment by Lonami** [comment]
Tomorrow :P

**Comment by Lonami** [comment]
Yep the bug is gone. Good job.
