### ISSUE TITLE
Irregular icon sizes

### ISSUE THREAD

**Issue by ImAnnoying** [stanipintjuk/Silverfish#2]
Some icons are small, while others are really big, leading to a somewhat confusing menu. Is there a way to scale all icons to the same size?

**Comment by ImAnnoying** [comment]
I'm unable to attach an image from mobile so here's a link to the screenshot. http://i.imgur.com/R3S4ETv.png

**Comment by stanipintjuk** [comment]
Yup, I just noticed this problem my self. It should be easy to fix (it is probably enough to set a constant width and height dp for the image view in list_item.xml and shortcut_item.xml) but I won't be able to do it until I come home on monday :/

**Comment by stanipintjuk** [comment]
I managed to find a good internet connection and pushed my commits so this issue should be solved
