### ISSUE TITLE
Quick Launch Buttons for calls, messages and so on...

### ISSUE THREAD

**Issue by Teyro** [stanipintjuk/Silverfish#20]
Is there a chance to get icons for calling, messages and contactadressbook working? Like on this Screenshot?
![screenshot_20160814-202255](https://cloud.githubusercontent.com/assets/4592523/17651004/0c226f42-625d-11e6-92c9-695345e5d0ff.png)

**Comment by stanipintjuk** [comment]
I don't see a need for it since the shortcuts on the home screen are already very easy to access

**Comment by Lonami** [comment]
Maybe as a feature: "Automatically organize the icon grid"

**Comment by stanipintjuk** [comment]
Organize in what way? Alphabetical order/relevance/last accessed?

**Comment by Lonami** [comment]
No, I meant, actually when dragging icons into the home screen, the grid is made automatically (if 4 elements or less, it's a 2x2 grid, else grows to a 3x3). So that would be with the feature enabled (as is now). If you disabled it, you should be able to place them wherever you wanted (instead of the grid being automatically made), thus being able to move them to the bottom part.

**Comment by Teyro** [comment]
Well i use Silverfish for testing and is miss the quick dial keys on the home screen very very much!! For exmaple if i want to take a call, i need to one the launcer swipe left push "Phone" Category select the dialer... Witg oiuck dial it is only one button i have to push..... It makes very much sence it can be optional but it would be nice to add four 1x1 wights at the button.... 

Best wishes from Hamburg Germany

**Comment by Teyro** [comment]
![screenshot_20160823-205634](https://cloud.githubusercontent.com/assets/4592523/17906068/f86f7362-6975-11e6-9726-be628dc6fd2a.png)

New Idea....Put the Tab Menu into a Hamburger menu so we have playce for 4x insteadt 3x app widgets ...Sounds good or not?

**Comment by stanipintjuk** [comment]
@Teyro But why don't you place it as a shortcut on the screen? Like this http://imgur.com/a/oCL5u

Maybe the launcher doesn't make it clear to the users that this is possible. sorry about that :( I should maybe add some kind of message

**Comment by Lonami** [comment]
> Maybe the launcher doesn't make it clear [...]

Not clear? 

> ### Usage
> 
> You can add shortcuts to the homescreen by going to the app drawer (swipe right) long click an app and then drag it into the homescreen. [...]

What @Teyro means is that he wants to be able to decide _where_ to place the applications' shortcuts (at the bottom, as if it were a dock) instead of them being placed centred on the screen:

> [...] add four 1x1 wights at the button [...]

Yet another thing to add to the database: shortcuts location, if this becomes implemented.

**Comment by Teyro** [comment]
Yes its true ;) I didnt find the Option it was not clear :D Now i can use Silverfish as my default launcher because usibilty is okay ;) 

And yes i want to decide where to put my widgets und shortcuts  ;) How it is now it is okay for daily use but not perfect ;) 

Thx for made Silverfish working enouth to replace Nova Launcher ;)
