### ISSUE TITLE
Add ability to reorder tabs

### ISSUE THREAD

**Issue by yllwboy** [stanipintjuk/Silverfish#27]
Many people using this launcher may not have this issue but this is kind of a big deal for me, I want to be able to set the tabs in the order I want them to be without having to rename them all and having to move all the apps manually. I have a lot of tabs since I have a lot of apps and while reordering tabs is very easy on proprietary Smart Launcher, it is an unnecessary hassle in the current version of Silverfish.

**Comment by Lonami** [comment]
This has already been discussed. It's probably something we end up adding to the launcher. However, it's good to know more people would use this!
