### ISSUE TITLE
Add ability to rearrange tabs

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [stanipintjuk/Silverfish#37]
Being able to rearrange tabs would be very nice. Currently it would seem that one would have to rename tabs and move apps around to achieve a similar task.

**Comment by Lonami** [comment]
It _is_ possible to rearrange tabs. I'm not aware, however, if F-Droid repositories have yet been updated with the latest changes, since I use a self-compiled version.

**Comment by DerVerruckteFuchs** [comment]
Ah, I'll keep an eye out for an update then.

**Comment by stanipintjuk** [comment]
I will try to update the f-droid version this weekend. Sorry for the long delay.
