### ISSUE TITLE
Let us see home screen without any widgets

### ISSUE THREAD

**Issue by alekksander** [stanipintjuk/Silverfish#38]
Please add possibility to see main screen without any distractions — just pure wallpaper (and status bar ofc)

**Comment by Lonami** [comment]
Hmm. Maybe a menu which pops up if tapping on the background:
- Hide/Show widget
- Change widget
- Change wallpaper

**Comment by alekksander** [comment]
my intention was to have it (short) tap—proof, but prone for sliding right.

**Comment by Lonami** [comment]
What about a double tap on the upper zone, where the widget is?

**Comment by alekksander** [comment]
i guess it could work, but it doesn't matter that much as there is nobody really working on this launcher 😢

**Comment by Lonami** [comment]
Closed on [commit#19244e](https://github.com/stanipintjuk/Silverfish/commit/19244e79d33fd0e0c2c96ab0ed46b8d21cdf709b), enjoy!
