### ISSUE TITLE
Full german translation

### ISSUE THREAD

**Issue by CrimsonFork** [stanipintjuk/Silverfish#45]
I've <a href="https://gist.github.com/2b5ecb46acbc71b10fb1a6be76cac20b">translated</a> the missing strings via <a href="https://github.com/LonamiWebs/Stringlate">Stringlate</a>.

**Comment by Lonami** [comment]
Sorry, why are some strings in Bulgarian (`bg`) and some others in German (`de`)? For example:
```xml
<resources>
    <string name="hint_widget_now_invisible">Dieses Widget wurde versteckt.</string>
    <string name="text_hold_to_change_widget">Задръжте за смяна на приспособлението</string>
</resources>
```

**Edit**: You probably had selected `bg` when you started translating for `de`. Then that's fine, thanks!

**Comment by Lonami** [comment]
Closed on [commit#c7dce0](https://github.com/stanipintjuk/Silverfish/commit/c7dce0c6f6f5cd66bec0c2c2bc2c72c8ee3d0ee6), I forgot to mention it on the commit message.
