### ISSUE TITLE
Native design

### ISSUE THREAD

**Issue by CrimsonFork** [stanipintjuk/Silverfish#46]
It would be cool if the pop up windows had the native android (holo/material) design.

**Comment by Lonami** [comment]
What popup windows? Do you mean the actions shown when long tapping a tab?

**Comment by CrimsonFork** [comment]
E.g. if you rename a tab the field still has the old android 1.x 2.x 3.x design.

**Comment by Lonami** [comment]
Alright saw the problem and got it fixed. Just want some feedback from @stanipintjuk and I'll `commit` and `push` the changes.

**Comment by CrimsonFork** [comment]
Cool, thanks!

Am 21. Dezember 2016 17:54:26 MEZ, schrieb Lonami <notifications@github.com>:
>Alright saw the problem and got it fixed. Just want some feedback from
>@stanipintjuk and I'll `commit` and `push` the changes.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/stanipintjuk/Silverfish/issues/46#issuecomment-268574323

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.
