### ISSUE TITLE
Dragging apps to the homescreen does not work

### ISSUE THREAD

**Issue by tpeg5stan** [stanipintjuk/Silverfish#51]
I am using a lenovo Moto G4 ; android 7.0 Nougat.

I am unable to add a shortcut to the home screen. When i long-press an app, I see the uninstall button at the bottom, and I can "move" it from a drawer to another, but impossible to switch to the homescreen and drop it.

What seems strange is that I perfectly remember I was able to do it once, and then (is it the upgrade from android 6 to 7 or a configuration I missed ?) I can't anymore.

Any idea ? I still find silverfish a very useful launcher, thanks for the good work.

**Comment by Lonami** [comment]
> is it the upgrade from android 6 to 7 or a configuration

Yes, that's the issue. I installed the F-Droid version to test (I had a custom build), and I'm able to drag shortcuts to the home screen (Android 6.0.1 Marshmallow). @stanipintjuk has the same issue on his Android 7 device, and I don't know why this can be.

**Comment by tpeg5stan** [comment]
So the problem seems to be Android 7...

I honestly do not see where the problem could comme from. I have tried to look at what is new with android 7 and did not see this kind of thing.

Is there a way to get past this problem by, for example, by adding a menu>add to launcher if we press the app longer ?
Or, like there is an "uninstall" option at the bottom of the screen, create a "add to home screen" at the top of the screen ?

This confuses me a bit...

**Comment by Lonami** [comment]
> by adding a menu>add to launcher if we press the app longer ?

:+1:, [`58794f6`](https://github.com/stanipintjuk/Silverfish/commit/58794f6b3a7a46d767f6a0b2f26d1f5247e826d1).
