### ISSUE TITLE
F-Droid package of v0.5 appears to be broken.

### ISSUE THREAD

**Issue by ghost** [stanipintjuk/Silverfish#52]
Downloading and installing Silverfish though F-Droid results in "Unfortunately, Silverfish has stopped." upon running. Installing the APK from [/releases](https://github.com/stanipintjuk/Silverfish/releases) however, runs as it should.

**Comment by Lonami** [comment]
I hope I didn't mess up, thanks for the report, let me test.

**Edit**: Ok, dang it.

**Comment by Lonami** [comment]
In the meantime, this is solved by clearing the application data (probably). Not an optimal solution, but I'm working on it now.

**Comment by Lonami** [comment]
Now we can just hope for F-Droid to build this ASAP. Thanks again for reporting.
