### ISSUE TITLE
Unable to move apps from app drawer to homescreen

### ISSUE THREAD

**Issue by chelmzy** [stanipintjuk/Silverfish#53]
Verizon HTC 10
Android 7.1.1 (LineagOS 14.1)

First off, thanks for making this launcher. It is certainly a breath of fresh air.

The only issue I am having is the inability to move apps from the app drawer to the homescreen. Whenever I pick the application up and drag it towards the homescreen it just doesn't rotate to the homescreen. Let me know if you would like more information about my device and I will help as best I can.

Thanks again

**Comment by Lonami** [comment]
#51, try to update to `v0.5.1` (do **not** update to `v0.5`! it's broken).

**Comment by chelmzy** [comment]
I apologize for the late reply but updating to v0.5.1 did not resolve the issue.

**Comment by Lonami** [comment]
> I apologize for the late reply but updating to v0.5.1 did not resolve the issue.

No, dragging doesn't work on Nougat and higher. But there is a workaround, hold the application you want and don't move it - then release (or what is the same, long tap it). Doesn't it show a menu to move it to the home screen?

**Comment by chelmzy** [comment]
Long pressing does not currently display the menu for me. I have tried the apk directly from github and also from F-Droid.

**Comment by Lonami** [comment]
Strange behaviour, using `v0.5.1` from F-Droid:

<img width="200px" src="https://cloud.githubusercontent.com/assets/6297805/24469059/910ad496-14ba-11e7-92d3-aded10703e53.gif" />

**Comment by MPArnold** [comment]
I cloned latest Silverfish to-day and had a good look at **TabbedAppDrawerFragment.java**   
The code to pop up the _Add to home screen_ option is bad and I could not find _any_ code that would move an app icon to the home page if it was dragged to the far right of the drawer.   
I made some mods and  it's working nicely for me (on Galaxy Tab S2 / Nougat) and I wonder what the next step is.  
I'm a newbie to GitHub and don't know how to contribute.

**Comment by Lonami** [comment]
@MPArnold fork the project (there's a button on the top right). Then clone it (`git clone <your url>`). Import that project and work there. `git add <changed files>`, `git commit` (put an useful message) and `git push`. Then from your fork, click "compare and pull request". For more details, use the web, it's your friend :)
