### ISSUE TITLE
Crash on Tapping Uninstalled App Shortcut

### ISSUE THREAD

**Issue by ghost** [stanipintjuk/Silverfish#62]
Icons for apps that have been uninstalled remain on the home screen (this also occurs in the left hand categories, but not for long as the app icons are refreshed upon changing tabs). Clicking on one of these "phantom" app icons causes the launcher to crash. Once silverfish is relaunched, the phantom icon disappears.

This bug is reproducible.

Relevant version information:
- Launcher version: 0.5.1
- Android version: 6.0.1
- Device: Samsung Galaxy S5 (not rooted)

**Comment by Lonami** [comment]
Ghosts hunting the application again. Anyway I just tried the upstream version and it doesn't fail, probably thanks to https://github.com/stanipintjuk/Silverfish/commit/4292031c67a6f2e8bc485140c35c928f9117621c. I will tag a new version shortly so the changes get pushed to F-Droid. Thanks!
