### ISSUE TITLE
Update to gradle v4.1 ?

### ISSUE THREAD

**Issue by thefzsalam** [stanipintjuk/Silverfish#70]
Android studio recommends to update gradle version.
> To take advantage of all the latest features (such as Instant Run), improvements and security fixes, we strongly recommend that you update the Android Gradle plugin to version 3.0.1 and Gradle to version 4.1.  You can learn more about this version of the plugin from the release notes.

I want to contribute to this project. Shall I continue with or without updating gradle for this project?

**Comment by MPArnold** [comment]
If you use Android Studio be aware that Gradle plugin 3.0.1 / gradle 4.1
require Android studio 3.

I spent half last night reverting to Android Studio 2.2.2 for the same
reasons described here
<https://stackoverflow.com/questions/47526000/how-to-fix-android-studio-3-0-logcat-log-print-delay-2-5-mins>
:

I am currently using  gradle plugin 2.3.3 and gradle 3.5 with AS  2.2.2 and
this supports Instant Run.

I have not had time to test IR yet.

**Comment by thefzsalam** [comment]
Yes, I use AS 3.0.1. 
Although, I have not yet run in to the issue yet. 
So, I'm continuing **without** updating gradle.

**Comment by Lonami** [comment]
> Shall I continue with or without updating gradle for this project?

You can upgrade and work locally with that but then just not `gid add`'ing the files. That's what I do. It's rather annoying that Android Studio insists so much on upgrading.

**Comment by thefzsalam** [comment]
The project builds fine in Android Studio v3.0.1. But when I type ./gradlew, the following error appears:
```

Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/farzeen/Projects/Feb 2018/Silverfish/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 3.3. Current version is 2.14.1. If using the gradle wrapper, try editing the distributionUrl in /home/farzeen/Projects/Feb 2018/Silverfish/gradle/wrapper/gradle-wrapper.properties to gradle-3.3-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.975 secs
```

**Comment by thefzsalam** [comment]
Just noticed that I had enabled the following settings:

![2018-02-18-181253_1366x768_scrot](https://user-images.githubusercontent.com/12694111/36351972-6963bbec-14d7-11e8-99af-f6b2ba010b25.png)

Local gradle version:

![2018-02-18-181308_1366x768_scrot](https://user-images.githubusercontent.com/12694111/36351971-69108a26-14d7-11e8-8c24-d6c5420ac84f.png)

**Comment by thefzsalam** [comment]
It builds fine when using the os supplied gradle (v4.5.1). It fails building with gradlew.
