### ISSUE TITLE
Single tap triggers widget selection

### ISSUE THREAD

**Issue by Lonami** [stanipintjuk/Silverfish#9]
### Steps to recreate

Find a widget which doesn't take all the space in the widget area _or_ one that doesn't take any action. Perform a tap somewhere not occupied by the widget.
### What happens

The widget selection triggers.
### Proof

![Tap bug](http://i.imgur.com/r647pom.gif)
- The first tap triggers the widget selection, when it shouldn't
- On the second tap I miss, nothing happens
- On the third tap, even with a little movement, the widget selection triggers
- On the fourth tap, I do hold my finger so you can appreciate the difference

**Comment by stanipintjuk** [comment]
Can confirm. I tested this with the firefox widget

**Comment by Lonami** [comment]
Even when `onInterceptTouchEvent(MotionEvent ev)` (under [LauncherAppWidgetHostView.java](https://github.com/stanipintjuk/Silverfish/blob/master/app/src/main/java/com/launcher/silverfish/LauncherAppWidgetHostView.java)) returns always `false`, the widget selection is still triggered. So we probably need to focus on the `widget_area` `FrameLayout` instead. Maybe intercept the touch events in a custom way as we did with the widget host view? But that is currently using the default `setOnLongClickListener`, it should work well... Awkward.

**Comment by stanipintjuk** [comment]
What if we simply remove any click listeners from the `widget_area` after a widget has been placed there?

**Comment by Lonami** [comment]
That's probably a good option.

**Comment by stanipintjuk** [comment]
Try it. If it works make a PR

**Comment by Lonami** [comment]
Will play with it ASAP 👍

**Comment by Lonami** [comment]
It couldn't be that easy... Didn't work. I've added `widget_area.setOnLongClickListener(null);` on `placeWidget(AppWidgetHostView hostView)` [here](https://github.com/stanipintjuk/Silverfish/blob/master/app/src/main/java/com/launcher/silverfish/HomeScreenFragment.java#L439) and it still fires. Even with a single tap. Isn't that supposed to prevent longClick from being fired?

The problem must be somewhere else.

**Comment by Lonami** [comment]
[This](https://github.com/stanipintjuk/Silverfish/blob/master/app/src/main/java/com/launcher/silverfish/LauncherAppWidgetHostView.java#L96) is the responsible. But it shouldn't be the case since it is _not_ a longClick!

**Comment by Lonami** [comment]
OK, `ACTION_UP` events are not fired for a simple reason:

> If you return false from `onTouch` method, no further events get delivered to the listener. You should return true at least in case of `event.getAction()` == `MotionEvent.ACTION_DOWN`.

From [this](http://stackoverflow.com/a/10192960/4759433) question. Let's see if that does the trick.
